### ISSUE TITLE
#[repr(C)] in mpmc

### ISSUE THREAD

**Issue by 0xpr03** [KyleMayes/npnc#1]
Hello,
is there a reason for `#[repr(c)]` in [mpmc queue](https://github.com/KyleMayes/npnc/blob/master/src/bounded/mpmc.rs#L157) ?
I believe this could hinder optimizations and is a little bit confusing as to why this is added.

**Comment by KyleMayes** [comment]
Note: This turned out at lot longer than I expected. I hope it answered your question!

`#[repr(C)]` is purposefully used to prevent the optimizer from shuffling fields around to improve performance.

### Foreword

I am not familiar with how much you already know about CPUs, so my apologies if you are already familiar with any of the following. I am also going to omit a bit of complexity here and there to try and get the high-level concepts across.

### Caches

CPUs have a cache (or, in many cases, multiple levels of caches oftentimes with multiple caches per level as well) to increase the performance of reading from and writing to locations in memory that have recently been read from or written to by the CPU.

These caches increase performance immensely because accessing main memory (i.e., RAM) is [*very* slow](https://stackoverflow.com/a/4087315) compared to typical CPU operations.

Complications arise in modern CPUs with their many cores. As mentioned earlier, modern CPUs often have multiple caches, and two particular cores can end up using different caches as their first level of cache. So what happens when one such core wants to read a value from a location in memory and another core wants to write to that same location in memory? Well it ain't good.

Since these cores are using different caches to read and write the same location in memory, we can't simply treat the caches as correct anymore because that would lead to the reader core reading stale values from its cache that don't reflect the new values written by the writer core to its cache. Now the CPU has to do a bunch of extra work keeping the caches synchronized with each other which degrades performance significantly.

Oftentimes, this is unavoidable, but at least if we aren't reading and writing to the same location in memory from different cores, we don't have to worry about this synchronization penalty, right? Nope.

### False Sharing

CPU caches don't operate on the level of individual bytes or words, they operate on the level of the ["cache line"](https://en.wikipedia.org/wiki/CPU_cache#CACHE-LINES), which is a contiguous sequence of bytes, usually [128 bytes at the most](https://github.com/KyleMayes/npnc/blob/8fb7d470752e14f2a8a449bf1df391453b60e3a9/src/lib.rs#L73-L77).

This introduces the problem of [false sharing](https://en.wikipedia.org/wiki/False_sharing), which is when you have the problem described above, but instead of the cores reading and writing the same location in memory, they are accessing *different* locations in memory that only happen to end up on the *same cache line.* When this happens, you pay the performance cost of the cache synchronization even though the cores aren't even touching each other's data!

Fortunately, there is a solution. When you have data you expect to be primarily accessed by different sets of cores, pad the data to ensure that the different sets of data will end up on different cache lines, thus eliminating (or at least reducing) the "false sharing" and minimizing the cache synchronization performance impact.

### `#[repr(C)]`

So this is why `#[repr(C)]` is used. It prevents the optimizer from altering the struct layout I have specified, which uses padding to ensure the values most commonly used by consumer threads don't end up on the same cache line as the values most commonly used by producer threads to eliminate the false sharing.

### Performance Impact

Just as bonus, here is an example of the performance impact of removing the padding from the bounded MPMC queue struct using the benchmarks in this crate.

#### Without Padding (false sharing)

```
throughput_bounded_mpmc
  13_721_825.07 operation/second
```

#### Padding (no false sharing)

```
throughput_bounded_mpmc
  77_054_566.33 operation/second
```

That's a 5.6x increase in throughput, all for the cost of making our MPMC queue a bit bigger.

**Comment by 0xpr03** [comment]
Wow, thanks for the answer. This was quite interesting and detailed.
I haven't looked into false sharing before, I expected hardware CAS to only trigger for each Atomic* variable specifically but it makes sense for cache coherence to use bigger chunks. Still, > 512 bit as default page on modern CPUs seems huge when you only have 1-2 Atomics in use. The difference in throughput is overwhelming.
Edit: misread Wikipedia, it's more than 512..
